name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version-file: ".python-version"

      - name: Checkout NVDA source
        run: git clone --depth 1 --no-recurse-submodules https://github.com/nvaccess/nvda.git ../nvda

      - name: Install dependencies
        run: uv sync

      - name: Run test suite via unittest
        run: uv run python -m unittest discover -s tests -t . -v
